## GDP

In [1]:
import numpy as np

In [2]:
countries_np = np.array(['Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon','Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia','Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland','Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico', 'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar','Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand', 'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe'])

In [3]:
countries_np

array(['Algeria', 'Angola', 'Argentina', 'Australia', 'Austria',
       'Bahamas', 'Bangladesh', 'Belarus', 'Belgium', 'Bhutan', 'Brazil',
       'Bulgaria', 'Cambodia', 'Cameroon', 'Chile', 'China', 'Colombia',
       'Cyprus', 'Denmark', 'El Salvador', 'Estonia', 'Ethiopia', 'Fiji',
       'Finland', 'France', 'Georgia', 'Ghana', 'Grenada', 'Guinea',
       'Haiti', 'Honduras', 'Hungary', 'India', 'Indonesia', 'Ireland',
       'Italy', 'Japan', 'Kenya', 'South Korea', 'Liberia', 'Malaysia',
       'Mexico', 'Morocco', 'Nepal', 'New Zealand', 'Norway', 'Pakistan',
       'Peru', 'Qatar', 'Russia', 'Singapore', 'South Africa', 'Spain',
       'Sweden', 'Switzerland', 'Thailand', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Venezuela',
       'Vietnam', 'Zimbabwe'], dtype='<U20')

In [4]:
countries_gdp_np = np.array([2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,229.6769525,2242.689259,27570.4852,23016.84778,1334.646773,402.6953275,6047.200797,394.1156638,385.5793827,1414.072488,5745.981529,837.7464011,1206.991065,27715.52837,18937.24998,39578.07441,478.2194906,16684.21278,279.2204061,5345.213415,6288.25324,1908.304416,274.8728621,14646.42094,40034.85063,672.1547506,3359.517402,36152.66676,3054.727742,33529.83052,3825.093781,15428.32098,33630.24604,39170.41371,2699.123242,21058.43643,28272.40661,37691.02733,9581.05659,5671.912202,757.4009286,347.7456605])

In [5]:
countries_gdp_np

array([ 2255.225482 ,   629.9553062, 11601.63022  , 25306.82494  ,
       27266.40335  , 19466.99052  ,   588.3691778,  2890.345675 ,
       24733.62696  ,  1445.760002 ,  4803.398244 ,  2618.876037 ,
         590.4521124,   665.7982328,  7122.938458 ,  2639.54156  ,
        3362.4656   , 15378.16704  , 30860.12808  ,  2579.115607 ,
        6525.541272 ,   229.6769525,  2242.689259 , 27570.4852   ,
       23016.84778  ,  1334.646773 ,   402.6953275,  6047.200797 ,
         394.1156638,   385.5793827,  1414.072488 ,  5745.981529 ,
         837.7464011,  1206.991065 , 27715.52837  , 18937.24998  ,
       39578.07441  ,   478.2194906, 16684.21278  ,   279.2204061,
        5345.213415 ,  6288.25324  ,  1908.304416 ,   274.8728621,
       14646.42094  , 40034.85063  ,   672.1547506,  3359.517402 ,
       36152.66676  ,  3054.727742 , 33529.83052  ,  3825.093781 ,
       15428.32098  , 33630.24604  , 39170.41371  ,  2699.123242 ,
       21058.43643  , 28272.40661  , 37691.02733  ,  9581.0565

In [17]:
#highest gdp value 
print(countries_gdp_np.max(), countries_gdp_np.min(),countries_gdp_np.mean(),countries_gdp_np.std(),countries_gdp_np.sum())

40034.85063 229.6769525 11289.409271639683 12743.828910617945 711232.7841133


In [25]:
#round the min and max values to 2 decimal places
np.round(countries_gdp_np.max(),2),np.round(countries_gdp_np.min(),2)

(40034.85, 229.68)

In [18]:
values_np = np.array([countries_gdp_np.max(), countries_gdp_np.min(),countries_gdp_np.mean(),countries_gdp_np.std(),countries_gdp_np.sum()])
values_np

array([4.00348506e+04, 2.29676952e+02, 1.12894093e+04, 1.27438289e+04,
       7.11232784e+05])

In [26]:
np.round(values_np, 2)

array([4.0034850e+04, 2.2968000e+02, 1.1289410e+04, 1.2743830e+04,
       7.1123278e+05])

In [30]:
countries_np[countries_gdp_np.argmax()],countries_np[countries_gdp_np.argmin()]

('Norway', 'Ethiopia')

## Print countries and gdp iteratively

In [33]:
# way 1
for i in range(len(countries_gdp_np)):
    print(countries_np[i],'\t',countries_gdp_np[i])

Algeria 	 2255.225482
Angola 	 629.9553062
Argentina 	 11601.63022
Australia 	 25306.82494
Austria 	 27266.40335
Bahamas 	 19466.99052
Bangladesh 	 588.3691778
Belarus 	 2890.345675
Belgium 	 24733.62696
Bhutan 	 1445.760002
Brazil 	 4803.398244
Bulgaria 	 2618.876037
Cambodia 	 590.4521124
Cameroon 	 665.7982328
Chile 	 7122.938458
China 	 2639.54156
Colombia 	 3362.4656
Cyprus 	 15378.16704
Denmark 	 30860.12808
El Salvador 	 2579.115607
Estonia 	 6525.541272
Ethiopia 	 229.6769525
Fiji 	 2242.689259
Finland 	 27570.4852
France 	 23016.84778
Georgia 	 1334.646773
Ghana 	 402.6953275
Grenada 	 6047.200797
Guinea 	 394.1156638
Haiti 	 385.5793827
Honduras 	 1414.072488
Hungary 	 5745.981529
India 	 837.7464011
Indonesia 	 1206.991065
Ireland 	 27715.52837
Italy 	 18937.24998
Japan 	 39578.07441
Kenya 	 478.2194906
South Korea 	 16684.21278
Liberia 	 279.2204061
Malaysia 	 5345.213415
Mexico 	 6288.25324
Morocco 	 1908.304416
Nepal 	 274.8728621
New Zealand 	 14646.42094
Norway 	 40034.

In [35]:
# way 2
for i,j in zip(countries_np,countries_gdp_np):
    print(i,j)

Algeria 2255.225482
Angola 629.9553062
Argentina 11601.63022
Australia 25306.82494
Austria 27266.40335
Bahamas 19466.99052
Bangladesh 588.3691778
Belarus 2890.345675
Belgium 24733.62696
Bhutan 1445.760002
Brazil 4803.398244
Bulgaria 2618.876037
Cambodia 590.4521124
Cameroon 665.7982328
Chile 7122.938458
China 2639.54156
Colombia 3362.4656
Cyprus 15378.16704
Denmark 30860.12808
El Salvador 2579.115607
Estonia 6525.541272
Ethiopia 229.6769525
Fiji 2242.689259
Finland 27570.4852
France 23016.84778
Georgia 1334.646773
Ghana 402.6953275
Grenada 6047.200797
Guinea 394.1156638
Haiti 385.5793827
Honduras 1414.072488
Hungary 5745.981529
India 837.7464011
Indonesia 1206.991065
Ireland 27715.52837
Italy 18937.24998
Japan 39578.07441
Kenya 478.2194906
South Korea 16684.21278
Liberia 279.2204061
Malaysia 5345.213415
Mexico 6288.25324
Morocco 1908.304416
Nepal 274.8728621
New Zealand 14646.42094
Norway 40034.85063
Pakistan 672.1547506
Peru 3359.517402
Qatar 36152.66676
Russia 3054.727742
Singapore 3

In [55]:
list_1 = list(zip(countries_np,countries_gdp_np))

In [56]:
dict_1 = dict()
for country, gdp in list_1:
    dict_1.setdefault(country, []).append(gdp)
print(dict_1)

{'Algeria': [2255.225482], 'Angola': [629.9553062], 'Argentina': [11601.63022], 'Australia': [25306.82494], 'Austria': [27266.40335], 'Bahamas': [19466.99052], 'Bangladesh': [588.3691778], 'Belarus': [2890.345675], 'Belgium': [24733.62696], 'Bhutan': [1445.760002], 'Brazil': [4803.398244], 'Bulgaria': [2618.876037], 'Cambodia': [590.4521124], 'Cameroon': [665.7982328], 'Chile': [7122.938458], 'China': [2639.54156], 'Colombia': [3362.4656], 'Cyprus': [15378.16704], 'Denmark': [30860.12808], 'El Salvador': [2579.115607], 'Estonia': [6525.541272], 'Ethiopia': [229.6769525], 'Fiji': [2242.689259], 'Finland': [27570.4852], 'France': [23016.84778], 'Georgia': [1334.646773], 'Ghana': [402.6953275], 'Grenada': [6047.200797], 'Guinea': [394.1156638], 'Haiti': [385.5793827], 'Honduras': [1414.072488], 'Hungary': [5745.981529], 'India': [837.7464011], 'Indonesia': [1206.991065], 'Ireland': [27715.52837], 'Italy': [18937.24998], 'Japan': [39578.07441], 'Kenya': [478.2194906], 'South Korea': [16684

In [57]:
print(dict(list_1))

{'Algeria': 2255.225482, 'Angola': 629.9553062, 'Argentina': 11601.63022, 'Australia': 25306.82494, 'Austria': 27266.40335, 'Bahamas': 19466.99052, 'Bangladesh': 588.3691778, 'Belarus': 2890.345675, 'Belgium': 24733.62696, 'Bhutan': 1445.760002, 'Brazil': 4803.398244, 'Bulgaria': 2618.876037, 'Cambodia': 590.4521124, 'Cameroon': 665.7982328, 'Chile': 7122.938458, 'China': 2639.54156, 'Colombia': 3362.4656, 'Cyprus': 15378.16704, 'Denmark': 30860.12808, 'El Salvador': 2579.115607, 'Estonia': 6525.541272, 'Ethiopia': 229.6769525, 'Fiji': 2242.689259, 'Finland': 27570.4852, 'France': 23016.84778, 'Georgia': 1334.646773, 'Ghana': 402.6953275, 'Grenada': 6047.200797, 'Guinea': 394.1156638, 'Haiti': 385.5793827, 'Honduras': 1414.072488, 'Hungary': 5745.981529, 'India': 837.7464011, 'Indonesia': 1206.991065, 'Ireland': 27715.52837, 'Italy': 18937.24998, 'Japan': 39578.07441, 'Kenya': 478.2194906, 'South Korea': 16684.21278, 'Liberia': 279.2204061, 'Malaysia': 5345.213415, 'Mexico': 6288.25324

In [61]:
d = {}
for i,j in zip(countries_np,countries_gdp_np):
    d[i]=j
print(d)

{'Algeria': 2255.225482, 'Angola': 629.9553062, 'Argentina': 11601.63022, 'Australia': 25306.82494, 'Austria': 27266.40335, 'Bahamas': 19466.99052, 'Bangladesh': 588.3691778, 'Belarus': 2890.345675, 'Belgium': 24733.62696, 'Bhutan': 1445.760002, 'Brazil': 4803.398244, 'Bulgaria': 2618.876037, 'Cambodia': 590.4521124, 'Cameroon': 665.7982328, 'Chile': 7122.938458, 'China': 2639.54156, 'Colombia': 3362.4656, 'Cyprus': 15378.16704, 'Denmark': 30860.12808, 'El Salvador': 2579.115607, 'Estonia': 6525.541272, 'Ethiopia': 229.6769525, 'Fiji': 2242.689259, 'Finland': 27570.4852, 'France': 23016.84778, 'Georgia': 1334.646773, 'Ghana': 402.6953275, 'Grenada': 6047.200797, 'Guinea': 394.1156638, 'Haiti': 385.5793827, 'Honduras': 1414.072488, 'Hungary': 5745.981529, 'India': 837.7464011, 'Indonesia': 1206.991065, 'Ireland': 27715.52837, 'Italy': 18937.24998, 'Japan': 39578.07441, 'Kenya': 478.2194906, 'South Korea': 16684.21278, 'Liberia': 279.2204061, 'Malaysia': 5345.213415, 'Mexico': 6288.25324

In [62]:
d['South Korea']

16684.21278

## Olympic 2012 medal tally

In [38]:
import numpy as np

In [43]:
country_np = np.array(['Great Britain', 'China', 'Russia', 'United States', 'Korea','Japan',
'Germany'])
gold_np = np.array([29, 38,24,46,13,7,11])
silver_np = np.array([17,28,25,28,8,14,11])
bronze_np = np.array([19,22,32,29,7,17,14])

In [45]:
country_np[gold_np.argmax()]

'United States'

In [46]:
# print countries having medals more than 20
gold_np>20

array([ True,  True,  True,  True, False, False, False])

In [48]:
above_20 = country_np[gold_np>20]
above_20

array(['Great Britain', 'China', 'Russia', 'United States'], dtype='<U13')

In [50]:
list(zip(gold_np,silver_np,bronze_np))

[(29, 17, 19),
 (38, 28, 22),
 (24, 25, 32),
 (46, 28, 29),
 (13, 8, 7),
 (7, 14, 17),
 (11, 11, 14)]

In [53]:
for i,j,k,l in zip(country_np,gold_np,silver_np,bronze_np):
    print(i,j,j+k+l)

Great Britain 29 65
China 38 88
Russia 24 81
United States 46 103
Korea 13 28
Japan 7 38
Germany 11 36
